development:
  log_level: debug
  log_file_path: ./pos.log 
  web_port: 8443
  provider:
    Adyen:
      #host: https://10.180.43.62:8443
      #host: https://10.180.43.63:8443
      host: https://10.180.43.64:8443
      #host: https://10.180.43.214:8443
      baseURL: /nexo
      verifyCA: False
      SaleID: POS
      ServiceID: 1000
      #POIID: P400Plus-804232069
      POIID: UX300-442300266

production:
  log_level: info
  log_file_path: ./pos.log
  web_port: 8443
  provider:
    Adyen:
      #host: https://10.180.43.62:8443
      #host: https://10.180.43.63:8443
      host: https://10.180.43.64:8443
      #host: https://10.180.43.214:8443
      baseURL: /nexo
      verifyCA: False
      SaleID: POS
      ServiceID: 1000
      POIID: P400Plus-804232069
      #POIID: UX300-442300266
      
